### ISSUE TITLE
qustion for getCoherenceTerm  implement

### ISSUE THREAD

**Issue by whymewhyme** [SuTanTank/BundledCameraPathVideoStabilization#1]
In Bundle class, the implement of function getCoherenceTerm  is  not similarity as the primary paper. The  paper is +P(Nr), why do you use P(Nr)/C(Nr)*C(Cur)?

**Comment by SuTanTank** [comment]
Yes, it's slightly different from the original bundled path paper. Instead of letting P be similar to its neighbor, I choose to make B be similar to its neighbor. This term is used for make the tiles in the output not to far away from each other, but the real term that cause those tiles departed is the transformation B, not P. I explained it in detail in my paper.

**Comment by SuTanTank** [comment]
Sorry I thought its another repo. The paper I mentioned is _Dynamic Video Stitching via Shakiness Removing_. In section III.A, paragraph starts with "Our Improvement: "

**Comment by whymewhyme** [comment]
thanks!
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Tan SU"<notifications@github.com>;
 发送时间: 2018年5月15日(星期二) 下午5:35
 收件人: "SuTanTank/BundledCameraPathVideoStabilization"<BundledCameraPathVideoStabilization@noreply.github.com>;
 抄送: "风"<1577065622@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [SuTanTank/BundledCameraPathVideoStabilization] qustion forgetCoherenceTerm implement (#1)

 

 
Sorry I thought its another repo. The paper I mentioned is Dynamic Video Stitching via Shakiness Removing. In section III.A, paragraph starts with "Our Improvement: "

**Comment by whymewhyme** [comment]
thank you! I have another question, that is the code calc the two Gauss, when calc the distance of two C, it just use C(x), C(y). then dose it can use all the param? thanks. 

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Tan SU"<notifications@github.com>;
 发送时间: 2018年5月15日(星期二) 下午5:35
 收件人: "SuTanTank/BundledCameraPathVideoStabilization"<BundledCameraPathVideoStabilization@noreply.github.com>;
 抄送: "风"<1577065622@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [SuTanTank/BundledCameraPathVideoStabilization] qustion forgetCoherenceTerm implement (#1)

 

 
Sorry I thought its another repo. The paper I mentioned is Dynamic Video Stitching via Shakiness Removing. In section III.A, paragraph starts with "Our Improvement: "

**Comment by SuTanTank** [comment]
As mentioned in Bundled paper, compute that weight is just an approximate estimation of how difference two Homographies are. Thus the original author chose to only use the "translation" part, i.e. these two elements in the 3x3 matrix.
