### ISSUE TITLE
Attempt to execute SCRIPT AsSimilarAsPossible as a function

### ISSUE THREAD

**Issue by slepkovanatal** [SuTanTank/BundledCameraPathVideoStabilization#2]
When I run run.m I get the error "Attempt to execute SCRIPT AsSimilarAsPossible as a function:
ProjectPath/BundledCameraPathVideoStabilization/Bundled/mex/AsSimilarAsPossible.m". What should I do?

**Comment by SuTanTank** [comment]
Hi, are you using Windows? AsSimiliarAspossible is a mex function and I only build the Windows version.

**Comment by slepkovanatal** [comment]
Yes, I understand. Where I can find this function for Ubuntu?

**Comment by SuTanTank** [comment]
cpp files are inside the same directory. You can build the Linux version from those sources.

**Comment by slepkovanatal** [comment]
Ok, thanks. Unfortunately, I am noob in matlab. Could You please write how to build the Linux version? Should I use mex or something else?

**Comment by SuTanTank** [comment]
I'm not sure how to build it in Linux. For the Windows version, I used Visual Studio and include Matlab's header files (mex.h etc) and also link Matlab's libraries.
