### ISSUE TITLE
Question about function optPath

### ISSUE THREAD

**Issue by semajping** [SuTanTank/BundledCameraPathVideoStabilization#3]
function optPath in Bundled.m:
"value = squeeze(**oP**(frameIndex, row, col, :, :)); " may be "value = squeeze(**obj.C**(frameIndex, row, col, :, :)); "?
value may be C(t) but not P(t)
I read the paper, but I'm not certain.

Thanks.

**Comment by SuTanTank** [comment]
Its been more than three years, so I may not remember the detail. But I made a change to the original bundled path energy function, which is explained in #1

**Comment by SuTanTank** [comment]
Yes, it should be C if following the paper strictly. But I found out using P leads to better result

**Comment by semajping** [comment]
Ok，thanks for your reply！
